// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD080rZsQ6Lb8oCGqqSxO1_9YzmpcroxhU',
    appId: '1:790616527024:web:f0ddabfc104e01684a2b75',
    messagingSenderId: '790616527024',
    projectId: 'to-do-list-cff46',
    authDomain: 'to-do-list-cff46.firebaseapp.com',
    storageBucket: 'to-do-list-cff46.appspot.com',
    measurementId: 'G-41XTDFV01Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnefQNGmWvFfobXMt3xU-5ip5DPJk0qYk',
    appId: '1:790616527024:android:1625cd8e8d28da954a2b75',
    messagingSenderId: '790616527024',
    projectId: 'to-do-list-cff46',
    storageBucket: 'to-do-list-cff46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN7c1ubr11uVfbKygOLqXtQKRFmMJiN1I',
    appId: '1:790616527024:ios:b7414e367bfea8dc4a2b75',
    messagingSenderId: '790616527024',
    projectId: 'to-do-list-cff46',
    storageBucket: 'to-do-list-cff46.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN7c1ubr11uVfbKygOLqXtQKRFmMJiN1I',
    appId: '1:790616527024:ios:b7414e367bfea8dc4a2b75',
    messagingSenderId: '790616527024',
    projectId: 'to-do-list-cff46',
    storageBucket: 'to-do-list-cff46.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD080rZsQ6Lb8oCGqqSxO1_9YzmpcroxhU',
    appId: '1:790616527024:web:90b6a4d7614afd314a2b75',
    messagingSenderId: '790616527024',
    projectId: 'to-do-list-cff46',
    authDomain: 'to-do-list-cff46.firebaseapp.com',
    storageBucket: 'to-do-list-cff46.appspot.com',
    measurementId: 'G-173887TN8Y',
  );
}
